### ISSUE TITLE
netCDF4/num2date and matplotlib

### ISSUE THREAD

**Issue by ds4g15** [cdr30/RapidMoc#4]
I'm experiencing an issue by which pcolormesh fails due to the `dts` array having type `real_datetime`. From looking around it seems this is due to a change in `netCDF4` where `num2date` previously returned `datetime` objects but now returns `real_datetime` objects, which matplotlib has issues with. 

The following workaround seems to patch things up (in `plotdiag.py`):

`import cftime; 
 import datetime; 
matplotlib.units.registry[cftime.real_datetime] = matplotlib.units.registry[datetime.datetime]`

but is a bit clunky.

**Comment by cdr30** [comment]
Thanks for raising this issue. I will take a look when I get some time, but it is not an immediate priority. 

Cheers,
Chris

**Comment by cdr30** [comment]
Hi, I have just pushed a new "experimental_python3" branch, which should fix this issue. if you have any problems let me know, otherwise I will merge in next few days.
